server:
  port: 5555
  servlet:
    context-path: /services
security:
  oauth2:
    resource:
      user-info-uri: https://graph.facebook.com/me    
spring:
  application:
    name: gateway-service
zuul:
  routes:
    employee:
      path: /employee/**
      serviceId: employee-service

hystrix:
  command:
    employee-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000                    

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  