server:
  port: 4444
spring:
  application:
    name: service1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka 
      
person:
 name: Subhojit
 
management:
  endpoints:
    web:
      exposure:
        include: "*"
         
 
